### ISSUE TITLE
PHP 8.2 support 

### ISSUE THREAD

**Issue by henkvalk** [productflowbv/magento2#1]
While installing the module on Magento 2.4.6 with php 8.2, we receive the following error during the `php bin/magento setup:upgrade`

```
Deprecated Functionality: Creation of dynamic property ProductFlowbv\Magento2\Setup\UpgradeData::$orderAttributes is deprecated in /vendor/productflowbv/magento2/Setup/UpgradeData.php on line 54
```

You need to declare the properties `$orderAttributes` and `$productAttributes` in your class `Setup/UpgradeData.php`

**Comment by remcom** [comment]
issue resolved
